server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # User Service Route (Register public, diğerleri korumalı)
        - id: user-service
          uri: http://user-service:8082
          predicates:
            - Path=/user/**
          filters:
            - AuthenticationFilter

        # Auth Service Route (Login public)
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**
          # Auth endpoint'leri public olduğu için filtre uygulamıyoruz